### ISSUE TITLE
Error when executing "bundle exec rake data:initialize"

### ISSUE THREAD

**Issue by Slayer741** [mattantonelli/ffxiv-collect#12]
Hello, followed every step, unfortunatly when i use "bundle exec rake data:initialize" it -- goes fine till "Setting initial collectable sources"
I get an error,

Setting initial collectable sources
rake aborted!
NoMethodError: undefined method `sources' for nil:NilClass

        model.find_by(name_en: row[0]).sources.find_or_create_by!(data)
                                      ^^^^^^^^
/Users/someone/Documents/ffxiv-collect/lib/tasks/sources.rake:38:in `block (4 levels) in <main>'
/Users/someonel/Documents/ffxiv-collect/lib/tasks/sources.rake:23:in `block (3 levels) in <main>'
/Users/someone/Documents/ffxiv-collect/lib/tasks/sources.rake:20:in `each'
/Users/someonel/Documents/ffxiv-collect/lib/tasks/sources.rake:20:in `block (2 levels) in <main>'
/Users/someone/Documents/ffxiv-collect/lib/tasks/all.rake:9:in `block (2 levels) in <main>'
/Users/someone/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
/Users/someone/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'
Tasks: TOP => sources:initialize

**Comment by mattantonelli** [comment]
Looks like an armoire item got renamed or something. This is resolved.
