### ISSUE TITLE
Filters in free company profile mount comparison screen

### ISSUE THREAD

**Issue by MrSoundless** [mattantonelli/ffxiv-collect#15]
It would be nice if we could hide/show specific FC members in the FC mount comparison window.
I've made a tampermonkey script for this, but it would be nice if it would be a built-in option in the website.
Tampermonkey script can be found here if interested: https://github.com/MrSoundless/FFXIVCollect-FC-mount-filters

Another option could be to make custom groups of people and have the mount comparison option that the FC has for those custom groups.

**Comment by mattantonelli** [comment]
> Another option could be to make custom groups of people and have the mount comparison option that the FC has for those custom groups.

https://ffxivcollect.com/groups

**Comment by MrSoundless** [comment]
Sorry, forgot to respond. Thanks that's exactly what I meant! Didn't know the option existed.
