### ISSUE TITLE
Feature request: unique identifier in table rows

### ISSUE THREAD

**Issue by dipnlik** [mattantonelli/ffxiv-collect#17]
Can you please add a unique identifier like character id or name to these table rows?

https://github.com/mattantonelli/ffxiv-collect/blob/6401e0f10a7ada377f5d0c65375e9662c8e49481/app/views/groups/collection.html.erb#L52-L66

I want to use the /fc/:id/mounts page but with just a few members of my FC.  Since I could not find a way to filter out specific characters from the FC list, I tried to use custom CSS to hide the rows I don't want, but without unique identifiers this is harder than it could be.

Thanks in advance!

**Comment by mattantonelli** [comment]
It sounds like a custom group is what you need. https://ffxivcollect.com/groups
