### ISSUE TITLE
Feature: Moogle Tomestones add market link to Other Items

### ISSUE THREAD

**Issue by Buzzman25** [mattantonelli/ffxiv-collect#25]
Can you add `<th scope="col" class="text-center"><%= fa_icon('dollar-sign') %></th>` after line 68?
https://github.com/mattantonelli/ffxiv-collect/blob/b5f4f436e75181cedc1284d8adc7de67938ad600/app/views/tomestones/index.html.erb#L65-L71

And `<td class="text-center"><%= market_link(reward.collectable) %></td>` after line 76?

https://github.com/mattantonelli/ffxiv-collect/blob/b5f4f436e75181cedc1284d8adc7de67938ad600/app/views/tomestones/index.html.erb#L72-L82

This way people can see what items in the Other Items are purchasable on the Market Board. I could open a Pull Request if this is easier for you.

**Comment by mattantonelli** [comment]
It's a bit more complicated as the `market_link` helper expects a collectable rather than an item, and currently prices are only being retrieved for collectables. I'll take a look at this.
